@baseUrl = http://localhost:8080
@productsPath = /api/v1/products

###
# Criar produto
POST {{baseUrl}}{{productsPath}}
Content-Type: application/json

{
  "name": "Mouse Gamer",
  "price": 199.90
}

###
# Buscar produto por ID
# (ajuste o ID conforme o retorno do POST)
@productId = 1
GET {{baseUrl}}{{productsPath}}/{{productId}}

###
# Atualizar produto
PUT {{baseUrl}}{{productsPath}}/{{productId}}
Content-Type: application/json

{
  "name": "Mouse Gamer Pro",
  "price": 249.90
}

###
# Deletar produto
DELETE {{baseUrl}}{{productsPath}}/{{productId}}